<testsuite errors="0" failures="0" tests="4" skipped="0" name="org.elasticsearch.recovery.RelocationIT" hostname="nohost.nodomain" time="3.557" timestamp="2016-03-29T17:29:10">
   <properties class="java.util.ArrayList">
      <property name="awt.toolkit" value="sun.lwawt.macosx.LWCToolkit"/>
      <property name="es.logger.level" value="WARN"/>
      <property name="file.encoding" value="UTF-8"/>
      <property name="file.encoding.pkg" value="sun.io"/>
      <property name="file.separator" value="/"/>
      <property name="ftp.nonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
      <property name="gopherProxySet" value="false"/>
      <property name="http.nonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
      <property name="java.awt.graphicsenv" value="sun.awt.CGraphicsEnvironment"/>
      <property name="java.awt.headless" value="true"/>
      <property name="java.awt.printerjob" value="sun.lwawt.macosx.CPrinterJob"/>
      <property name="java.class.path" value="/Users/ogbonnayacngwu/CSE2410_spring2016_projectileDysfunction/core/build/classes/test:/Users/ogbonnayacngwu/CSE2410_spring2016_projectileDysfunction/core/build/resources/test:/Users/ogbonnayacngwu/CSE2410_spring2016_projectileDysfunction/core/build/classes/main:/Users/ogbonnayacngwu/CSE2410_spring2016_projectileDysfunction/core/build/resources/main:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-core/5.5.0-snapshot-1721183/f6854c65c7f4c6d9de583f4daa4fd3ae8a3800f1/lucene-core-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-analyzers-common/5.5.0-snapshot-1721183/69e187ef1d2d9c9570363eb4186821e0341df5b8/lucene-analyzers-common-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-backward-codecs/5.5.0-snapshot-1721183/fa00a45ff9bc6a4df44db81f2e4e44ea94bf88e/lucene-backward-codecs-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-grouping/5.5.0-snapshot-1721183/e996e6c723eb415ba2cfa7f5e98bbf194a4918dd/lucene-grouping-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-highlighter/5.5.0-snapshot-1721183/3b7a5d97b10885f16eb53deb15d64c942b9f9fdb/lucene-highlighter-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-join/5.5.0-snapshot-1721183/e4dda3eeb76e340aa4713a3b20d68c4a1504e505/lucene-join-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-memory/5.5.0-snapshot-1721183/800442a5d7612ce4c8748831871b4d436a50554e/lucene-memory-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-misc/5.5.0-snapshot-1721183/bdf184de9b5773c7af3ae908af78eeb1e512470c/lucene-misc-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-queries/5.5.0-snapshot-1721183/fc59de52bd2c7e420edfd235723cb8b0dd44e92d/lucene-queries-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-queryparser/5.5.0-snapshot-1721183/1d341e6a4f11f3170773ccffdbe6815b45967e3d/lucene-queryparser-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-sandbox/5.5.0-snapshot-1721183/a1b02c2b595ac92f45f0d2be03841a3a7fcae1f1/lucene-sandbox-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-spatial/5.5.0-snapshot-1721183/e3ea422b56734329fb6974e9cf9f66478adb5793/lucene-spatial-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-spatial3d/5.5.0-snapshot-1721183/5eadbd4e63120b59ab6445e39489205f98420471/lucene-spatial3d-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-suggest/5.5.0-snapshot-1721183/a336287e65d082535f02a8427666dbe46b1b9b74/lucene-suggest-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.elasticsearch/securesm/1.0/c0c6cf986ba0057390bfcc80c366a0e3157f944b/securesm-1.0.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/commons-cli/commons-cli/1.3.1/1303efbc4b181e5a58bf2e967dc156a3132b97c0/commons-cli-1.3.1.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/com.carrotsearch/hppc/0.7.1/8b5057f74ea378c0150a1860874a3ebdcb713767/hppc-0.7.1.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/joda-time/joda-time/2.8.2/d27c24204c5e507b16fec01006b3d0f1ec42aed4/joda-time-2.8.2.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.joda/joda-convert/1.2/35ec554f0cd00c956cc69051514d9488b1374dec/joda-convert-1.2.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.6.2/123f29333b2c6b3516b14252b6e93226bfcd6e37/jackson-core-2.6.2.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-smile/2.6.2/395d18c1a1dd730b8026ee59c4067e5d2b45ba6e/jackson-dataformat-smile-2.6.2.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml/2.6.2/4ae23088dd3fae47c66843f2e4251d7255ee140e/jackson-dataformat-yaml-2.6.2.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-cbor/2.6.2/1e13c575f914c83761bb8e2aca7dfd9e4c647579/jackson-dataformat-cbor-2.6.2.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/io.netty/netty/3.10.5.Final/9ca7d55d246092bddd29b867706e2f6c7db701a0/netty-3.10.5.Final.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/com.tdunning/t-digest/3.0/84ccf145ac2215e6bfa63baa3101c0af41017cfc/t-digest-3.0.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.hdrhistogram/HdrHistogram/2.1.6/7495feb7f71ee124bd2a7e7d83590e296d71d80e/HdrHistogram-2.1.6.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/com.spatial4j/spatial4j/0.5/6e16edaf6b1ba76db7f08c2f3723fce3b358ecc3/spatial4j-0.5.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/com.vividsolutions/jts/1.13/3ccfb9b60f04d71add996a666ceb8902904fd805/jts-1.13.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/log4j/log4j/1.2.17/5af35056b4d257e4b64b9e8069c0746e8b08629f/log4j-1.2.17.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/log4j/apache-log4j-extras/1.2.17/85863614d82185d7e51fe21c00aa9117a523a8b6/apache-log4j-extras-1.2.17.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.6.2/8619e95939167fb37245b5670135e4feb0ec7d50/slf4j-api-1.6.2.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/4.1.0/1c12d070e602efd8021891cdd7fd18bc129372d4/jna-4.1.0.jar:/Users/ogbonnayacngwu/CSE2410_spring2016_projectileDysfunction/test/framework/build/libs/framework-3.0.0-SNAPSHOT.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/com.carrotsearch.randomizedtesting/randomizedtesting-runner/2.3.2/307965917fe8a22b7ee72deba39ef4b8e6ebc069/randomizedtesting-runner-2.3.2.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/junit/junit/4.11/4e031bb61df09069aeb2bffb4019e7a5034a4ee0/junit-4.11.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-all/1.3/63a21ebc981131004ad02e0434e799fd7f3a8d5a/hamcrest-all-1.3.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-test-framework/5.5.0-snapshot-1721183/a8d851d0ad82182b3a02f4b30c336e7aa0e173cb/lucene-test-framework-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-codecs/5.5.0-snapshot-1721183/8aa59442b028c7a2c1a516accb6142a8910ba5fc/lucene-codecs-5.5.0-snapshot-1721183.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.3.6/4c47155e3e6c9a41a28db36680b828ced53b8af4/httpclient-4.3.6.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore/4.3.3/f91b7a4aadc5cf486df6e4634748d7dd7a73f06d/httpcore-4.3.3.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/commons-logging/commons-logging/1.1.3/f6f66e966c70a83ffbdb6f17a0919eaf7c8aca7f/commons-logging-1.1.3.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.10/4b95f4897fa13f2cd904aee711aeafc0c5295cd8/commons-codec-1.10.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/org.elasticsearch/securemock/1.2/98201d4ad5ac93f6b415ae9172d52b5e7cda490e/securemock-1.2.jar:/Users/ogbonnayacngwu/.gradle/caches/modules-2/files-2.1/com.carrotsearch.randomizedtesting/junit4-ant/2.3.2/dc8f03f6111974092491f35b8269eb0fc57f52f7/junit4-ant-2.3.2.jar"/>
      <property name="java.class.version" value="52.0"/>
      <property name="java.endorsed.dirs" value="/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/lib/endorsed"/>
      <property name="java.ext.dirs" value="/Users/ogbonnayacngwu/Library/Java/Extensions:/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/lib/ext:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java"/>
      <property name="java.home" value="/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre"/>
      <property name="java.io.tmpdir" value="./temp"/>
      <property name="java.library.path" value="/Users/ogbonnayacngwu/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:."/>
      <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
      <property name="java.runtime.version" value="1.8.0_11-b12"/>
      <property name="java.specification.name" value="Java Platform API Specification"/>
      <property name="java.specification.vendor" value="Oracle Corporation"/>
      <property name="java.specification.version" value="1.8"/>
      <property name="java.vendor" value="Oracle Corporation"/>
      <property name="java.vendor.url" value="http://java.oracle.com/"/>
      <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
      <property name="java.version" value="1.8.0_11"/>
      <property name="java.vm.info" value="mixed mode"/>
      <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
      <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
      <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
      <property name="java.vm.specification.version" value="1.8"/>
      <property name="java.vm.vendor" value="Oracle Corporation"/>
      <property name="java.vm.version" value="25.11-b03"/>
      <property name="junit4.childvm.count" value="4"/>
      <property name="junit4.childvm.cwd" value="/Users/ogbonnayacngwu/CSE2410_spring2016_projectileDysfunction/core/build/testrun/integTest/J0"/>
      <property name="junit4.childvm.id" value="0"/>
      <property name="junit4.memory.total" value="514850816"/>
      <property name="junit4.pidString" value="27392@host37-246.aruba.fit.edu"/>
      <property name="junit4.processors" value="8"/>
      <property name="line.separator" value="
"/>
      <property name="os.arch" value="x86_64"/>
      <property name="os.name" value="Mac OS X"/>
      <property name="os.version" value="10.11.4"/>
      <property name="path.separator" value=":"/>
      <property name="socksNonProxyHosts" value="local|*.local|169.254/16|*.169.254/16"/>
      <property name="sun.arch.data.model" value="64"/>
      <property name="sun.boot.class.path" value="/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/classes"/>
      <property name="sun.boot.library.path" value="/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/lib"/>
      <property name="sun.cpu.endian" value="little"/>
      <property name="sun.cpu.isalist" value=""/>
      <property name="sun.io.unicode.encoding" value="UnicodeBig"/>
      <property name="sun.java.command" value="com.carrotsearch.ant.tasks.junit4.slave.SlaveMainSafe -eventsfile /Users/ogbonnayacngwu/CSE2410_spring2016_projectileDysfunction/core/build/testrun/integTest/temp/junit4-J0-20160329_172724_554.events @/Users/ogbonnayacngwu/CSE2410_spring2016_projectileDysfunction/core/build/testrun/integTest/temp/junit4-J0-20160329_172724_554.suites -stdin"/>
      <property name="sun.java.launcher" value="SUN_STANDARD"/>
      <property name="sun.jnu.encoding" value="UTF-8"/>
      <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
      <property name="sun.os.patch.level" value="unknown"/>
      <property name="tests.artifact" value="core"/>
      <property name="tests.ifNoTests" value="fail"/>
      <property name="tests.maven" value="true"/>
      <property name="tests.prefix" value="tests"/>
      <property name="tests.security.manager" value="true"/>
      <property name="tests.seed" value="4AA6DECDBC490785"/>
      <property name="tests.task" value=":core:integTest"/>
      <property name="user.country" value="US"/>
      <property name="user.dir" value="/Users/ogbonnayacngwu/CSE2410_spring2016_projectileDysfunction/core/build/testrun/integTest/J0"/>
      <property name="user.home" value="/Users/ogbonnayacngwu"/>
      <property name="user.language" value="en"/>
      <property name="user.name" value="ogbonnayacngwu"/>
      <property name="user.timezone" value="America/New_York"/>
   </properties>
   <testcase classname="org.elasticsearch.recovery.RelocationIT" name="testRelocationWhileRefreshing" time="0.463"/>
   <testcase classname="org.elasticsearch.recovery.RelocationIT" name="testRelocationWhileIndexingRandom" time="2.279"/>
   <testcase classname="org.elasticsearch.recovery.RelocationIT" name="testSimpleRelocationNoIndexing" time="0.373"/>
   <testcase classname="org.elasticsearch.recovery.RelocationIT" name="testCancellationCleansTempFiles" time="0.409"/>
   <system-out><![CDATA[[2016-03-29 17:29:10,674][DEBUG][org.elasticsearch.indices.recovery] [node_t0] using max_bytes_per_sec[40mb]
[2016-03-29 17:29:10,746][DEBUG][org.elasticsearch.indices.recovery] [node_t1] using max_bytes_per_sec[6mb]
[2016-03-29 17:29:10,777][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] started recovery from {node_t0}{qCBxCz9JQ-mp9_Ic2Q6bTA}{local}{local[125]}[mode=>local], id [305]
[2016-03-29 17:29:10,778][TRACE][org.elasticsearch.indices.recovery] [node_t1] collecting local files for [test][0] [305]
[2016-03-29 17:29:10,782][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] starting recovery from {node_t0}{qCBxCz9JQ-mp9_Ic2Q6bTA}{local}{local[125]}[mode=>local]
[2016-03-29 17:29:10,782][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t1}{AVgNCU4aTO28HLhU3mD7PA}{local}{local[127]}[mode=>local], mark_as_relocated false
[2016-03-29 17:29:10,782][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [-1] for recovery
[2016-03-29 17:29:10,798][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{AVgNCU4aTO28HLhU3mD7PA}{local}{local[127]}[mode=>local]: recovering [segments_1], does not exists in remote
[2016-03-29 17:29:10,799][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{AVgNCU4aTO28HLhU3mD7PA}{local}{local[127]}[mode=>local]: recovering_files [1] with total_size [130b], reusing_files [0] with total_size [0b]
[2016-03-29 17:29:10,813][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{AVgNCU4aTO28HLhU3mD7PA}{local}{local[127]}[mode=>local]: prepare remote engine for translog
[2016-03-29 17:29:10,829][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{AVgNCU4aTO28HLhU3mD7PA}{local}{local[127]}[mode=>local]: remote engine start took [15ms]
[2016-03-29 17:29:10,829][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{AVgNCU4aTO28HLhU3mD7PA}{local}{local[127]}[mode=>local]: took [0s]
[2016-03-29 17:29:10,829][TRACE][org.elasticsearch.indices.recovery] [node_t0] snapshot translog for recovery. current size is [26]
[2016-03-29 17:29:10,829][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{AVgNCU4aTO28HLhU3mD7PA}{local}{local[127]}[mode=>local]: sending transaction log operations
[2016-03-29 17:29:10,833][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] sent final batch of [26][1.5kb] (total: [26]) translog operations to {node_t1}{AVgNCU4aTO28HLhU3mD7PA}{local}{local[127]}[mode=>local]
[2016-03-29 17:29:10,833][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{AVgNCU4aTO28HLhU3mD7PA}{local}{local[127]}[mode=>local]: took [4.5ms]
[2016-03-29 17:29:10,833][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{AVgNCU4aTO28HLhU3mD7PA}{local}{local[127]}[mode=>local]
[2016-03-29 17:29:10,867][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{AVgNCU4aTO28HLhU3mD7PA}{local}{local[127]}[mode=>local]: took [33.4ms]
[2016-03-29 17:29:10,867][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] marking recovery from {node_t0}{qCBxCz9JQ-mp9_Ic2Q6bTA}{local}{local[125]}[mode=>local] as done, id [305]
[2016-03-29 17:29:10,868][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] recovery completed from {node_t0}{qCBxCz9JQ-mp9_Ic2Q6bTA}{local}{local[125]}[mode=>local], took[89ms]
   phase1: recovered_files [1] with total_size of [130b], took [0s], throttling_wait [0s]
         : reusing_files   [0] with total_size of [0b]
   phase2: start took [15ms]
         : recovered [26] transaction log operations, took [4ms]

[2016-03-29 17:29:11,118][DEBUG][org.elasticsearch.indices.recovery] [node_t0] using max_bytes_per_sec[40mb]
[2016-03-29 17:29:11,162][DEBUG][org.elasticsearch.indices.recovery] [node_t1] using max_bytes_per_sec[119mb]
[2016-03-29 17:29:11,172][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] started recovery from {node_t0}{OOfqSAm1QNSboxUlp1IMvw}{local}{local[129]}[mode=>local], id [306]
[2016-03-29 17:29:11,172][TRACE][org.elasticsearch.indices.recovery] [node_t1] collecting local files for [test][0] [306]
[2016-03-29 17:29:11,172][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] starting recovery from {node_t0}{OOfqSAm1QNSboxUlp1IMvw}{local}{local[129]}[mode=>local]
[2016-03-29 17:29:11,172][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local], mark_as_relocated false
[2016-03-29 17:29:11,172][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [-1] for recovery
[2016-03-29 17:29:11,173][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: recovering [segments_1], does not exists in remote
[2016-03-29 17:29:11,173][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: recovering_files [1] with total_size [130b], reusing_files [0] with total_size [0b]
[2016-03-29 17:29:11,177][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: prepare remote engine for translog
[2016-03-29 17:29:11,184][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: remote engine start took [6.6ms]
[2016-03-29 17:29:11,184][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: took [0s]
[2016-03-29 17:29:11,184][TRACE][org.elasticsearch.indices.recovery] [node_t0] snapshot translog for recovery. current size is [0]
[2016-03-29 17:29:11,184][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: sending transaction log operations
[2016-03-29 17:29:11,184][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] no translog operations to send to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]
[2016-03-29 17:29:11,184][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] sent final batch of [0][0b] (total: [0]) translog operations to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]
[2016-03-29 17:29:11,184][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: took [156micros]
[2016-03-29 17:29:11,184][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]
[2016-03-29 17:29:11,185][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: took [285micros]
[2016-03-29 17:29:11,185][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] marking recovery from {node_t0}{OOfqSAm1QNSboxUlp1IMvw}{local}{local[129]}[mode=>local] as done, id [306]
[2016-03-29 17:29:11,185][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] recovery completed from {node_t0}{OOfqSAm1QNSboxUlp1IMvw}{local}{local[129]}[mode=>local], took[13ms]
   phase1: recovered_files [1] with total_size of [130b], took [0s], throttling_wait [0s]
         : reusing_files   [0] with total_size of [0b]
   phase2: start took [6ms]
         : recovered [0] transaction log operations, took [0s]

[2016-03-29 17:29:11,233][DEBUG][org.elasticsearch.indices.recovery] [node_t2] using max_bytes_per_sec[40mb]
[2016-03-29 17:29:12,334][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] started recovery from {node_t0}{OOfqSAm1QNSboxUlp1IMvw}{local}{local[129]}[mode=>local], id [307]
[2016-03-29 17:29:12,334][TRACE][org.elasticsearch.indices.recovery] [node_t2] collecting local files for [test][0] [307]
[2016-03-29 17:29:12,334][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] starting recovery from {node_t0}{OOfqSAm1QNSboxUlp1IMvw}{local}{local[129]}[mode=>local]
[2016-03-29 17:29:12,335][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t2}{73QQskD2R8KJFvSEIv5SSw}{local}{local[132]}[mode=>local], mark_as_relocated false
[2016-03-29 17:29:12,335][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [-1] for recovery
[2016-03-29 17:29:12,335][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{73QQskD2R8KJFvSEIv5SSw}{local}{local[132]}[mode=>local]: recovering [segments_1], does not exists in remote
[2016-03-29 17:29:12,335][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{73QQskD2R8KJFvSEIv5SSw}{local}{local[132]}[mode=>local]: recovering_files [1] with total_size [130b], reusing_files [0] with total_size [0b]
[2016-03-29 17:29:12,352][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{73QQskD2R8KJFvSEIv5SSw}{local}{local[132]}[mode=>local]: prepare remote engine for translog
[2016-03-29 17:29:12,362][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{73QQskD2R8KJFvSEIv5SSw}{local}{local[132]}[mode=>local]: remote engine start took [10.1ms]
[2016-03-29 17:29:12,362][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{73QQskD2R8KJFvSEIv5SSw}{local}{local[132]}[mode=>local]: took [0s]
[2016-03-29 17:29:12,362][TRACE][org.elasticsearch.indices.recovery] [node_t0] snapshot translog for recovery. current size is [365]
[2016-03-29 17:29:12,362][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t2}{73QQskD2R8KJFvSEIv5SSw}{local}{local[132]}[mode=>local]: sending transaction log operations
[2016-03-29 17:29:12,435][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] sent final batch of [365][83.2kb] (total: [365]) translog operations to {node_t2}{73QQskD2R8KJFvSEIv5SSw}{local}{local[132]}[mode=>local]
[2016-03-29 17:29:12,435][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t2}{73QQskD2R8KJFvSEIv5SSw}{local}{local[132]}[mode=>local]: took [72.7ms]
[2016-03-29 17:29:12,435][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t2}{73QQskD2R8KJFvSEIv5SSw}{local}{local[132]}[mode=>local]
[2016-03-29 17:29:12,478][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t2}{73QQskD2R8KJFvSEIv5SSw}{local}{local[132]}[mode=>local]: took [42.6ms]
[2016-03-29 17:29:12,478][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] marking recovery from {node_t0}{OOfqSAm1QNSboxUlp1IMvw}{local}{local[129]}[mode=>local] as done, id [307]
[2016-03-29 17:29:12,479][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] recovery completed from {node_t0}{OOfqSAm1QNSboxUlp1IMvw}{local}{local[129]}[mode=>local], took[144ms]
   phase1: recovered_files [1] with total_size of [130b], took [0s], throttling_wait [0s]
         : reusing_files   [0] with total_size of [0b]
   phase2: start took [10ms]
         : recovered [365] transaction log operations, took [72ms]

[2016-03-29 17:29:12,522][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] started recovery from {node_t0}{OOfqSAm1QNSboxUlp1IMvw}{local}{local[129]}[mode=>local], id [308]
[2016-03-29 17:29:12,522][TRACE][org.elasticsearch.indices.recovery] [node_t1] collecting local files for [test][0] [308]
[2016-03-29 17:29:12,522][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] starting recovery from {node_t0}{OOfqSAm1QNSboxUlp1IMvw}{local}{local[129]}[mode=>local]
[2016-03-29 17:29:12,522][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local], mark_as_relocated false
[2016-03-29 17:29:12,523][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [-1] for recovery
[2016-03-29 17:29:12,523][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: recovering [segments_1], does not exists in remote
[2016-03-29 17:29:12,524][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: recovering_files [1] with total_size [130b], reusing_files [0] with total_size [0b]
[2016-03-29 17:29:12,544][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: prepare remote engine for translog
[2016-03-29 17:29:12,555][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: remote engine start took [11.2ms]
[2016-03-29 17:29:12,555][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: took [0s]
[2016-03-29 17:29:12,555][TRACE][org.elasticsearch.indices.recovery] [node_t0] snapshot translog for recovery. current size is [642]
[2016-03-29 17:29:12,556][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: sending transaction log operations
[2016-03-29 17:29:12,675][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] sent final batch of [642][149.2kb] (total: [642]) translog operations to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]
[2016-03-29 17:29:12,675][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: took [119.4ms]
[2016-03-29 17:29:12,675][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]
[2016-03-29 17:29:12,714][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{wZHFUKArTzm3NJyQorxaYw}{local}{local[130]}[mode=>local]: took [39.2ms]
[2016-03-29 17:29:12,715][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] marking recovery from {node_t0}{OOfqSAm1QNSboxUlp1IMvw}{local}{local[129]}[mode=>local] as done, id [308]
[2016-03-29 17:29:12,715][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] recovery completed from {node_t0}{OOfqSAm1QNSboxUlp1IMvw}{local}{local[129]}[mode=>local], took[192ms]
   phase1: recovered_files [1] with total_size of [130b], took [0s], throttling_wait [0s]
         : reusing_files   [0] with total_size of [0b]
   phase2: start took [11ms]
         : recovered [642] transaction log operations, took [119ms]

[2016-03-29 17:29:13,397][DEBUG][org.elasticsearch.indices.recovery] [node_t0] using max_bytes_per_sec[40mb]
[2016-03-29 17:29:13,553][DEBUG][org.elasticsearch.indices.recovery] [node_t1] using max_bytes_per_sec[2mb]
[2016-03-29 17:29:13,575][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] started recovery from {node_t0}{-kxZqgqSQrGxnm-zEAH4Nw}{local}{local[135]}[mode=>local], id [309]
[2016-03-29 17:29:13,575][TRACE][org.elasticsearch.indices.recovery] [node_t1] collecting local files for [test][0] [309]
[2016-03-29 17:29:13,577][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] starting recovery from {node_t0}{-kxZqgqSQrGxnm-zEAH4Nw}{local}{local[135]}[mode=>local]
[2016-03-29 17:29:13,577][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t1}{gRKsxrQKRRqZ16eWVLmnrQ}{local}{local[137]}[mode=>local], mark_as_relocated false
[2016-03-29 17:29:13,577][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [2] for recovery
[2016-03-29 17:29:13,585][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{gRKsxrQKRRqZ16eWVLmnrQ}{local}{local[137]}[mode=>local]: recovering [_0.cfe], does not exists in remote
[2016-03-29 17:29:13,585][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{gRKsxrQKRRqZ16eWVLmnrQ}{local}{local[137]}[mode=>local]: recovering [_0.si], does not exists in remote
[2016-03-29 17:29:13,585][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{gRKsxrQKRRqZ16eWVLmnrQ}{local}{local[137]}[mode=>local]: recovering [_0.cfs], does not exists in remote
[2016-03-29 17:29:13,585][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{gRKsxrQKRRqZ16eWVLmnrQ}{local}{local[137]}[mode=>local]: recovering [segments_2], does not exists in remote
[2016-03-29 17:29:13,585][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{gRKsxrQKRRqZ16eWVLmnrQ}{local}{local[137]}[mode=>local]: recovering_files [4] with total_size [3.4kb], reusing_files [0] with total_size [0b]
[2016-03-29 17:29:13,615][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{gRKsxrQKRRqZ16eWVLmnrQ}{local}{local[137]}[mode=>local]: prepare remote engine for translog
[2016-03-29 17:29:13,631][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{gRKsxrQKRRqZ16eWVLmnrQ}{local}{local[137]}[mode=>local]: remote engine start took [15.5ms]
[2016-03-29 17:29:13,631][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{gRKsxrQKRRqZ16eWVLmnrQ}{local}{local[137]}[mode=>local]: took [0s]
[2016-03-29 17:29:13,631][TRACE][org.elasticsearch.indices.recovery] [node_t0] snapshot translog for recovery. current size is [10]
[2016-03-29 17:29:13,631][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{gRKsxrQKRRqZ16eWVLmnrQ}{local}{local[137]}[mode=>local]: sending transaction log operations
[2016-03-29 17:29:13,634][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] sent final batch of [10][430b] (total: [10]) translog operations to {node_t1}{gRKsxrQKRRqZ16eWVLmnrQ}{local}{local[137]}[mode=>local]
[2016-03-29 17:29:13,634][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase2] to {node_t1}{gRKsxrQKRRqZ16eWVLmnrQ}{local}{local[137]}[mode=>local]: took [3.4ms]
[2016-03-29 17:29:13,635][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{gRKsxrQKRRqZ16eWVLmnrQ}{local}{local[137]}[mode=>local]
[2016-03-29 17:29:13,671][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] finalizing recovery to {node_t1}{gRKsxrQKRRqZ16eWVLmnrQ}{local}{local[137]}[mode=>local]: took [36.9ms]
[2016-03-29 17:29:13,672][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] marking recovery from {node_t0}{-kxZqgqSQrGxnm-zEAH4Nw}{local}{local[135]}[mode=>local] as done, id [309]
[2016-03-29 17:29:13,672][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] recovery completed from {node_t0}{-kxZqgqSQrGxnm-zEAH4Nw}{local}{local[135]}[mode=>local], took[96ms]
   phase1: recovered_files [4] with total_size of [3.4kb], took [0s], throttling_wait [0s]
         : reusing_files   [0] with total_size of [0b]
   phase2: start took [15ms]
         : recovered [10] transaction log operations, took [3ms]

[2016-03-29 17:29:13,772][DEBUG][org.elasticsearch.indices.recovery] [node_t0] using max_bytes_per_sec[40mb]
[2016-03-29 17:29:13,829][DEBUG][org.elasticsearch.indices.recovery] [node_t1] using max_bytes_per_sec[40mb]
[2016-03-29 17:29:13,876][DEBUG][org.elasticsearch.indices.recovery] [node_t2] using max_bytes_per_sec[187mb]
[2016-03-29 17:29:13,994][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] started recovery from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local], id [310]
[2016-03-29 17:29:13,994][TRACE][org.elasticsearch.indices.recovery] [node_t1] collecting local files for [test][0] [310]
[2016-03-29 17:29:13,995][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] starting recovery from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local]
[2016-03-29 17:29:13,995][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local], mark_as_relocated false
[2016-03-29 17:29:13,995][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [2] for recovery
[2016-03-29 17:29:13,996][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_0.cfe], does not exists in remote
[2016-03-29 17:29:13,996][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_0.si], does not exists in remote
[2016-03-29 17:29:13,996][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_0.cfs], does not exists in remote
[2016-03-29 17:29:13,996][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_1.cfs], does not exists in remote
[2016-03-29 17:29:13,997][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_1.cfe], does not exists in remote
[2016-03-29 17:29:13,997][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_1.si], does not exists in remote
[2016-03-29 17:29:13,997][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [segments_2], does not exists in remote
[2016-03-29 17:29:13,997][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_1_1.liv], does not exists in remote
[2016-03-29 17:29:13,997][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_0_1.liv], does not exists in remote
[2016-03-29 17:29:13,997][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering_files [9] with total_size [9.7kb], reusing_files [0] with total_size [0b]
[2016-03-29 17:29:14,019][WARN ][org.elasticsearch.indices.recovery] [node_t0] 0 Remote file corruption on node {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local], recovering name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]. local checksum OK
org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
	at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
	at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-29 17:29:14,023][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] Got exception on recovery
RemoteTransportException[[node_t1][local[141]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[139]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-03-29 17:29:14,024][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] failing recovery from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local], id [310]. Send shard failure: [true]
[2016-03-29 17:29:14,024][WARN ][org.elasticsearch.indices.cluster] [node_t1] [[test][0]] marking and sending shard failed due to [failed recovery]
RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local] into {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]]; nested: RemoteTransportException[[node_t1][local[141]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:271)
	at org.elasticsearch.indices.recovery.RecoveryTarget.access$1100(RecoveryTarget.java:79)
	at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:521)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[node_t1][local[141]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[139]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-03-29 17:29:14,027][WARN ][org.elasticsearch.cluster.action.shard] [node_t0] [test][0] received shard failed for [test][0], node[_-tzPw8XQrirYTwRIA0ZoQ], [R], v[3], s[INITIALIZING], a[id=2uMR8nhIRoml5a0KVqxXxA], unassigned_info[[reason=REPLICA_ADDED], at[2016-03-29T21:29:13.984Z]], indexUUID [JQtzZgCWQaCIAa9xpAgsMg], message [failed recovery], failure [RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local] into {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]]; nested: RemoteTransportException[[node_t1][local[141]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]; ]
RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local] into {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]]; nested: RemoteTransportException[[node_t1][local[141]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:271)
	at org.elasticsearch.indices.recovery.RecoveryTarget.access$1100(RecoveryTarget.java:79)
	at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:521)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[node_t1][local[141]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[139]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-03-29 17:29:14,027][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] closing IndexOutput file [VerifyingIndexOutput(out=FSIndexOutput(path="/Users/ogbonnayacngwu/CSE2410_spring2016_projectileDysfunction/core/build/testrun/integTest/J0/temp/org.elasticsearch.recovery.RelocationIT_4AA6DECDBC490785-001/tempDir-004/data/TEST-CHILD_VM=[0]-CLUSTER_SEED=[-2816702042850140850]-HASH=[14406DC0B693ED68]-cluster/nodes/1/indices/test/0/index/recovery.1459286953994.segments_2"))]
[2016-03-29 17:29:14,028][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1459286953994._1_1.liv]
[2016-03-29 17:29:14,028][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1459286953994._0_1.liv]
[2016-03-29 17:29:14,028][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1459286953994.segments_2]
[2016-03-29 17:29:14,043][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] started recovery from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local], id [311]
[2016-03-29 17:29:14,046][TRACE][org.elasticsearch.indices.recovery] [node_t2] collecting local files for [test][0] [311]
[2016-03-29 17:29:14,047][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] starting recovery from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local]
[2016-03-29 17:29:14,047][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local], mark_as_relocated false
[2016-03-29 17:29:14,047][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [2] for recovery
[2016-03-29 17:29:14,048][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local]: recovering [_0.cfe], does not exists in remote
[2016-03-29 17:29:14,048][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local]: recovering [_0.si], does not exists in remote
[2016-03-29 17:29:14,048][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local]: recovering [_0.cfs], does not exists in remote
[2016-03-29 17:29:14,048][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local]: recovering [_1.cfs], does not exists in remote
[2016-03-29 17:29:14,048][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local]: recovering [_1.cfe], does not exists in remote
[2016-03-29 17:29:14,048][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local]: recovering [_1.si], does not exists in remote
[2016-03-29 17:29:14,049][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local]: recovering [segments_2], does not exists in remote
[2016-03-29 17:29:14,049][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local]: recovering [_1_1.liv], does not exists in remote
[2016-03-29 17:29:14,049][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local]: recovering [_0_1.liv], does not exists in remote
[2016-03-29 17:29:14,049][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local]: recovering_files [9] with total_size [9.7kb], reusing_files [0] with total_size [0b]
[2016-03-29 17:29:14,059][WARN ][org.elasticsearch.indices.recovery] [node_t0] 0 Remote file corruption on node {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local], recovering name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]. local checksum OK
org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
	at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
	at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-29 17:29:14,060][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] Got exception on recovery
RemoteTransportException[[node_t2][local[142]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[139]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-03-29 17:29:14,061][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] failing recovery from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local], id [311]. Send shard failure: [true]
[2016-03-29 17:29:14,061][WARN ][org.elasticsearch.indices.cluster] [node_t2] [[test][0]] marking and sending shard failed due to [failed recovery]
RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local] into {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local]]; nested: RemoteTransportException[[node_t2][local[142]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:271)
	at org.elasticsearch.indices.recovery.RecoveryTarget.access$1100(RecoveryTarget.java:79)
	at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:521)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[node_t2][local[142]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[139]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-03-29 17:29:14,063][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] closing IndexOutput file [VerifyingIndexOutput(out=FSIndexOutput(path="/Users/ogbonnayacngwu/CSE2410_spring2016_projectileDysfunction/core/build/testrun/integTest/J0/temp/org.elasticsearch.recovery.RelocationIT_4AA6DECDBC490785-001/tempDir-004/data/TEST-CHILD_VM=[0]-CLUSTER_SEED=[-2816702042850140850]-HASH=[14406DC0B693ED68]-cluster/nodes/2/indices/test/0/index/recovery.1459286954043.segments_2"))]
[2016-03-29 17:29:14,064][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1459286954043._1_1.liv]
[2016-03-29 17:29:14,064][WARN ][org.elasticsearch.cluster.action.shard] [node_t0] [test][0] received shard failed for [test][0], node[vgDOCbZoSdya9pRECI3FqQ], [R], v[5], s[INITIALIZING], a[id=fYMGbOpxToOjwjkILfGPSQ], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-03-29T21:29:14.032Z], details[failed recovery, failure RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local] into {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]]; nested: RemoteTransportException[[node_t1][local[141]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]; ]], indexUUID [JQtzZgCWQaCIAa9xpAgsMg], message [failed recovery], failure [RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local] into {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local]]; nested: RemoteTransportException[[node_t2][local[142]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]; ]
RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local] into {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local]]; nested: RemoteTransportException[[node_t2][local[142]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:271)
	at org.elasticsearch.indices.recovery.RecoveryTarget.access$1100(RecoveryTarget.java:79)
	at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:521)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[node_t2][local[142]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[139]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-03-29 17:29:14,064][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1459286954043._0_1.liv]
[2016-03-29 17:29:14,065][TRACE][org.elasticsearch.indices.recovery] [node_t2] [test][0] cleaning temporary file [recovery.1459286954043.segments_2]
[2016-03-29 17:29:14,072][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] started recovery from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local], id [312]
[2016-03-29 17:29:14,073][TRACE][org.elasticsearch.indices.recovery] [node_t1] collecting local files for [test][0] [312]
[2016-03-29 17:29:14,073][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] starting recovery from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local]
[2016-03-29 17:29:14,073][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] starting recovery to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local], mark_as_relocated false
[2016-03-29 17:29:14,073][TRACE][org.elasticsearch.indices.recovery] [node_t0] captured translog id [2] for recovery
[2016-03-29 17:29:14,075][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_0.cfe], does not exists in remote
[2016-03-29 17:29:14,075][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_0.si], does not exists in remote
[2016-03-29 17:29:14,075][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_0.cfs], does not exists in remote
[2016-03-29 17:29:14,075][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_1.cfs], does not exists in remote
[2016-03-29 17:29:14,075][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_1.cfe], does not exists in remote
[2016-03-29 17:29:14,075][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_1.si], does not exists in remote
[2016-03-29 17:29:14,075][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [segments_2], does not exists in remote
[2016-03-29 17:29:14,075][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_1_1.liv], does not exists in remote
[2016-03-29 17:29:14,075][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering [_0_1.liv], does not exists in remote
[2016-03-29 17:29:14,075][TRACE][org.elasticsearch.indices.recovery] [node_t0] [test][0] recovery [phase1] to {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]: recovering_files [9] with total_size [9.7kb], reusing_files [0] with total_size [0b]
[2016-03-29 17:29:14,080][WARN ][org.elasticsearch.indices.recovery] [node_t0] 0 Remote file corruption on node {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local], recovering name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]. local checksum OK
org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
	at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
	at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
	at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-03-29 17:29:14,081][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] Got exception on recovery
RemoteTransportException[[node_t1][local[141]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[139]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-03-29 17:29:14,082][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] failing recovery from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local], id [312]. Send shard failure: [true]
[2016-03-29 17:29:14,082][WARN ][org.elasticsearch.indices.cluster] [node_t1] [[test][0]] marking and sending shard failed due to [failed recovery]
RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local] into {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]]; nested: RemoteTransportException[[node_t1][local[141]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:271)
	at org.elasticsearch.indices.recovery.RecoveryTarget.access$1100(RecoveryTarget.java:79)
	at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:521)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[node_t1][local[141]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[139]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-03-29 17:29:14,085][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] closing IndexOutput file [VerifyingIndexOutput(out=FSIndexOutput(path="/Users/ogbonnayacngwu/CSE2410_spring2016_projectileDysfunction/core/build/testrun/integTest/J0/temp/org.elasticsearch.recovery.RelocationIT_4AA6DECDBC490785-001/tempDir-004/data/TEST-CHILD_VM=[0]-CLUSTER_SEED=[-2816702042850140850]-HASH=[14406DC0B693ED68]-cluster/nodes/1/indices/test/0/index/recovery.1459286954072.segments_2"))]
[2016-03-29 17:29:14,085][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1459286954072._1_1.liv]
[2016-03-29 17:29:14,085][WARN ][org.elasticsearch.cluster.action.shard] [node_t0] [test][0] received shard failed for [test][0], node[_-tzPw8XQrirYTwRIA0ZoQ], [R], v[7], s[INITIALIZING], a[id=b5KK0LOkRrGhwZonAgMq-Q], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-03-29T21:29:14.065Z], details[failed recovery, failure RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local] into {node_t2}{vgDOCbZoSdya9pRECI3FqQ}{local}{local[142]}[mode=>local]]; nested: RemoteTransportException[[node_t2][local[142]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]; ]], indexUUID [JQtzZgCWQaCIAa9xpAgsMg], message [failed recovery], failure [RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local] into {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]]; nested: RemoteTransportException[[node_t1][local[141]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]; ]
RecoveryFailedException[[test][0]: Recovery failed from {node_t0}{oMTQFnaHQ_S4HSWRFk1Xww}{local}{local[139]}[mode=>local] into {node_t1}{_-tzPw8XQrirYTwRIA0ZoQ}{local}{local[141]}[mode=>local]]; nested: RemoteTransportException[[node_t1][local[141]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:271)
	at org.elasticsearch.indices.recovery.RecoveryTarget.access$1100(RecoveryTarget.java:79)
	at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:521)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[node_t1][local[141]][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
Caused by: [test][[test][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:137)
	at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:123)
	at org.elasticsearch.indices.recovery.RecoverySource.access$100(RecoverySource.java:52)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
	at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:129)
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
	at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [test][[test][0]] RecoverFilesRecoveryException[Failed to transfer [9] files with total size of [9.7kb]]; nested: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]];
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:316)
	at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
	... 11 more
Caused by: RemoteTransportException[[File corruption occurred on recovery but checksums are ok]]
	Suppressed: RemoteTransportException[[node_t0][local[139]][internal:index/shard/recovery/file_chunk]]; nested: CorruptIndexException[checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))];
	Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?) : expected=o5r7r7 actual=19lb0xn (resource=name [segments_2], length [257], checksum [o5r7r7], writtenBy [5.5.0]) (resource=VerifyingIndexOutput(segments_2))
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.readAndCompareChecksum(Store.java:1350)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeByte(Store.java:1329)
		at org.elasticsearch.index.store.Store$LuceneVerifyingIndexOutput.writeBytes(Store.java:1358)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
		at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:432)
		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:65)
		at org.elasticsearch.transport.local.LocalTransport$2.doRun(LocalTransport.java:296)
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
[2016-03-29 17:29:14,085][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1459286954072.segments_2]
[2016-03-29 17:29:14,086][TRACE][org.elasticsearch.indices.recovery] [node_t1] [test][0] cleaning temporary file [recovery.1459286954072._0_1.liv]
[2016-03-29 17:29:14,134][WARN ][org.elasticsearch.test.transport] [node_t1] Transport response handler not found of id [63]
]]></system-out>
   <system-err><![CDATA[]]></system-err>
</testsuite>